GET http://localhost:3000/api/students
Content-Type: application/json

HTTP/1.1 200 OK
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
Date: Tue, 30 Sep 2025 07:23:36 GMT
Connection: close
Transfer-Encoding: chunked

[
  {
    "id": 1,
    "first_name": "Name",
    "last_name": "Namov",
    "middle_name": "Namevovich",
    "groupId": 4
  },
  {
    "id": 2,
    "first_name": "Imia",
    "last_name": "Familivov",
    "middle_name": "Middlevovich",
    "groupId": 3
  },
  {
    "id": 3,
    "first_name": "Ivan",
    "last_name": "Ivanov",
    "middle_name": "Ivanovich",
    "groupId": 1
  }
]